import { CargoJob, Certification, DriverProfile, Vehicle, ChatMessage } from './types';

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh-1',
    makeModel: 'Tata Winger Reefer Chiller',
    licensePlate: 'MH-12-TR-902',
    type: 'Refrigerated Van',
    isReeferCertified: true,
    isHazmatCertified: false,
    reeferTempMin: -25,
    reeferTempMax: 10,
    maxPayloadKg: 1450,
    odometer: '48,220 km',
    inspectionStatus: 'verified',
  },
  {
    id: 'veh-2',
    makeModel: 'Mahindra Bolero Maxi Truck',
    licensePlate: 'DL-01-WG-118',
    type: 'Dry Cargo Van',
    isReeferCertified: false,
    isHazmatCertified: false,
    maxPayloadKg: 1850,
    odometer: '62,910 km',
    inspectionStatus: 'verified',
  },
  {
    id: 'veh-3',
    makeModel: 'Eicher Pro 2049 Shielded Flatbed',
    licensePlate: 'KA-04-HZ-441',
    type: 'Hazmat Flatbed',
    isReeferCertified: false,
    isHazmatCertified: true,
    maxPayloadKg: 3200,
    odometer: '89,450 km',
    inspectionStatus: 'verified',
  },
];

export const INITIAL_DRIVER: DriverProfile = {
  id: 'drv-8821',
  fullName: 'Rajesh Kumar',
  phone: '+91 98452 19820',
  callSign: 'Unit 44-Echo',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
  memberSince: 'March 2023',
  trustRating: 4.98,
  totalTrips: 642,
  onTimePercent: 99,
  coldChainCompliancePercent: 100,
  acceptanceRatePercent: 97,
  selectedVehicleId: 'veh-1',
};

export const INITIAL_CERTIFICATIONS: Certification[] = [
  {
    id: 'cert-1',
    title: 'Commercial Heavy Cargo License',
    category: 'Driver',
    status: 'verified',
    issuedDate: 'Jan 15, 2024',
    expiryDate: 'Jan 15, 2027',
    badgeNumber: 'CDL-A-99421',
    verifiedBy: 'State Transport Bureau',
    description: 'Class A commercial heavy freight operator clearance',
  },
  {
    id: 'cert-2',
    title: 'Active Cold-Chain Sensor Calibration',
    category: 'Vehicle',
    status: 'verified',
    issuedDate: 'Feb 10, 2025',
    expiryDate: 'Feb 10, 2026',
    badgeNumber: 'CC-CAL-7029',
    verifiedBy: 'ThermoKing Telemetry Lab',
    description: 'Certified active cooling unit with real-time temperature telemetry',
  },
  {
    id: 'cert-3',
    title: 'Biological Cargo & Vaccine Handling',
    category: 'Regulated Cargo',
    status: 'verified',
    issuedDate: 'Nov 01, 2024',
    expiryDate: 'Nov 01, 2025',
    badgeNumber: 'BIO-SEC-418',
    verifiedBy: 'Health Logistics Authority',
    description: 'Pharma cold-chain handling & unbroken custody protocol',
  },
  {
    id: 'cert-4',
    title: 'Vehicle Annual Mechanical Inspection',
    category: 'Vehicle',
    status: 'due',
    issuedDate: 'Mar 25, 2024',
    expiryDate: 'Mar 25, 2025',
    badgeNumber: 'INSP-2024-88',
    verifiedBy: 'DOT Certified Inspector',
    description: 'Annual brake, tire, and structural load check (Renewal due in 14 days)',
  },
  {
    id: 'cert-5',
    title: 'Hazardous Class 3 Flammable Liquids',
    category: 'Regulated Cargo',
    status: 'expired',
    issuedDate: 'Feb 01, 2024',
    expiryDate: 'Feb 01, 2025',
    badgeNumber: 'HAZ-FLAM-103',
    verifiedBy: 'Safety Council',
    description: 'Class 3 liquid hazmat transport permit (Expired - Tap to upload renewal)',
  },
];

export const INITIAL_ACTIVE_JOB: CargoJob = {
  id: 'job-9014',
  orderNumber: 'CRG-8820',
  title: 'Pharma Vaccines (Chilled 2°C to 8°C)',
  cargoType: 'cold_chain',
  weight: '145 kg (4 insulated containers)',
  dimensions: '120 x 80 x 60 cm',
  packagesCount: 4,
  requiredVehicleType: 'Refrigerated Van',
  pickup: {
    facilityName: 'Metro BioDepot Hub',
    address: '440 Industrial Parkway, Dock #4',
    dock: 'Loading Bay 4 (Cold staging area)',
    contactName: 'Elena Rostova (Dock Supervisor)',
    contactPhone: '+1 (555) 301-8844',
    readyTime: 'Ready now',
    distanceAway: '2.4 km (6 min)',
    notes: 'Enter through Gate 3. Ring chime at cold door. Do not leave container at room temp.',
  },
  dropoff: {
    facilityName: 'Memorial Hospital East Pharmacy',
    address: '800 Health Sciences Drive, Receiving Dock B',
    dock: 'Dock B - Medical Intake',
    recipientName: 'Dr. James Chen (Chief Pharmacist)',
    recipientPhone: '+1 (555) 774-9912',
    requiredBy: 'Today by 3:30 PM',
    distanceFromPickup: '14.2 km (22 min)',
    securityCode: '4829',
    notes: 'Pharmacy basement receiving. Temp logger will be verified by Dr. Chen upon transfer.',
  },
  baseFare: 950.0,
  surcharges: [],
  tripStatus: 'heading_to_pickup',
  coldChain: {
    targetTempMin: 2.0,
    targetTempMax: 8.0,
    currentTemp: 3.8,
    unit: '°C',
    status: 'optimal',
    sensorId: 'SNSR-REEFER-902',
    lastPing: 'Just now (Live)',
  },
  specialInstructions: [
    'Keep cargo inside refrigerated cargo bay at all times.',
    'Confirm recipient temperature log at handoff.',
    'Obtain direct recipient code & signature.',
  ],
};

export const AVAILABLE_JOBS: CargoJob[] = [
  {
    id: 'job-9015',
    orderNumber: 'CRG-8825',
    title: 'Emergency Plasma Units (Cold-Chain)',
    cargoType: 'cold_chain',
    weight: '80 kg (2 coolers)',
    dimensions: '60 x 50 x 40 cm',
    packagesCount: 2,
    requiredVehicleType: 'Refrigerated Van',
    pickup: {
      facilityName: 'Blood Bank Central',
      address: '120 Donor Way, North Bay',
      dock: 'Dispatch Bay 1',
      contactName: 'Sarah Jenkins',
      contactPhone: '+1 (555) 202-9988',
      readyTime: 'Ready in 10 min',
      distanceAway: '4.1 km (11 min)',
      notes: 'Priority medical run. Chilled transport mandatory.',
    },
    dropoff: {
      facilityName: 'St. Jude Trauma Center',
      address: '550 Hope Blvd, ER Receiving',
      dock: 'ER Loading Zone',
      recipientName: 'Nurse Lead Thompson',
      recipientPhone: '+1 (555) 883-1122',
      requiredBy: 'Immediate',
      distanceFromPickup: '9.8 km (15 min)',
      securityCode: '7712',
      notes: 'Direct handoff at ER nurse station.',
    },
    baseFare: 1100.0,
    surcharges: [],
    tripStatus: 'heading_to_pickup',
    coldChain: {
      targetTempMin: 1.0,
      targetTempMax: 6.0,
      currentTemp: 3.2,
      unit: '°C',
      status: 'optimal',
      sensorId: 'SNSR-REEFER-902',
      lastPing: '2m ago',
    },
    specialInstructions: ['Priority medical transport', 'Target temp 1°C to 6°C'],
  },
  {
    id: 'job-9016',
    orderNumber: 'CRG-8829',
    title: 'Precision CNC Machined Parts (Dry Cargo)',
    cargoType: 'standard',
    weight: '340 kg (1 pallet)',
    dimensions: '120 x 100 x 90 cm',
    packagesCount: 1,
    requiredVehicleType: 'Dry Cargo Van',
    pickup: {
      facilityName: 'Apex Precision Metalworks',
      address: '210 Foundry St, Bay 7',
      dock: 'Dock 7',
      contactName: 'Bob Miller',
      contactPhone: '+1 (555) 441-2299',
      readyTime: 'Ready now',
      distanceAway: '3.0 km (7 min)',
      notes: 'Forklift loaded onto cargo bed. Pallet strapped.',
    },
    dropoff: {
      facilityName: 'Aero Assembly Plant 3',
      address: '990 Aerospace Blvd, Gate 1',
      dock: 'Inbound Warehouse C',
      recipientName: 'Frankie Ward',
      recipientPhone: '+1 (555) 919-4455',
      requiredBy: 'Today by 5:00 PM',
      distanceFromPickup: '18.5 km (28 min)',
      securityCode: '1903',
      notes: 'Forklift offload at dock C.',
    },
    baseFare: 720.0,
    surcharges: [],
    tripStatus: 'heading_to_pickup',
    specialInstructions: ['Dry freight', 'Heavy pallet — dock offload required'],
  },
  {
    id: 'job-9017',
    orderNumber: 'CRG-8832',
    title: 'Regulated Industrial Solvents (UN 1993 Class 3)',
    cargoType: 'regulated_hazmat',
    weight: '420 kg (2 secure steel drums)',
    dimensions: '90 x 90 x 110 cm',
    packagesCount: 2,
    requiredVehicleType: 'Hazmat Flatbed',
    hazardClass: 'Class 3 Flammable Liquid (UN 1993)',
    pickup: {
      facilityName: 'ChemTech Logistics Terminal',
      address: '100 Chemical Row, Compound B',
      dock: 'Hazmat Staging Bay 2',
      contactName: 'Capt. Donald Brooks',
      contactPhone: '+1 (555) 772-0044',
      readyTime: 'Ready now',
      distanceAway: '6.5 km (14 min)',
      notes: 'Driver must carry placard kit & spill containment pads.',
    },
    dropoff: {
      facilityName: 'Polymer Coating Solutions',
      address: '1400 Refinery Ave, Tank Farm Gate',
      dock: 'Chemical Receiving Tank 4',
      recipientName: 'David Lee (Hazmat Tech)',
      recipientPhone: '+1 (555) 606-3388',
      requiredBy: 'Today by 4:00 PM',
      distanceFromPickup: '26.0 km (35 min)',
      securityCode: '9941',
      notes: 'Check containment seals before offload.',
    },
    baseFare: 1550.0,
    surcharges: [],
    tripStatus: 'heading_to_pickup',
    specialInstructions: [
      'Class 3 Flammable Liquid placard required',
      'Locking cargo containment mandatory',
      'Verified Hazmat vehicle endorsement required',
    ],
  },
];

export const INITIAL_CHAT: ChatMessage[] = [
  {
    id: 'msg-1',
    sender: 'customer',
    senderName: 'Dr. James Chen (Hospital)',
    text: 'Hello Marcus, confirming we have staff at Receiving Dock B ready for the vaccine drop.',
    timestamp: '1:42 PM',
  },
  {
    id: 'msg-2',
    sender: 'driver',
    senderName: 'Marcus (You)',
    text: "Thanks Dr. Chen! I am currently en route to the depot for pickup. Chiller is pre-cooled to 3.8°C.",
    timestamp: '1:44 PM',
  },
  {
    id: 'msg-3',
    sender: 'customer',
    senderName: 'Dr. James Chen (Hospital)',
    text: 'Great. Please ring the pharmacy intercom upon arrival so we can unlock the cold lift.',
    timestamp: '1:45 PM',
  },
];

export const QUICK_CHAT_OPTIONS = [
  "I've arrived at the facility gate",
  "Waiting at dock / staging bay",
  "Cargo loaded, chiller secured",
  "En route to dropoff now (ETA 20m)",
  "At dropoff door, ready to unload",
  "Please send receiver with signature code",
];

export const PAST_TRIPS_HISTORY = [
  {
    id: 'hist-1',
    orderNumber: 'CRG-8790',
    title: 'Biotech Diagnostic Kits (Chilled)',
    date: 'Yesterday, 4:15 PM',
    cargoType: 'cold_chain' as const,
    pickup: 'BioGen Lab (Dock 2)',
    dropoff: 'City Diagnostics (Central)',
    distance: '18.4 km',
    duration: '32 min',
    baseFare: 1100.0,
    surchargeTotal: 250.0,
    surcharges: [
      {
        id: 'sur-hist-1',
        reason: 'Dock Delay (40 min wait)',
        amount: 250.0,
        status: 'approved' as const,
        requestedAt: 'Yesterday 3:20 PM',
        approvedAt: 'Yesterday 3:35 PM',
      },
    ],
    totalPayout: 1350.0,
    status: 'Completed',
    verifiedTemp: '4.1°C (Optimal)',
  },
  {
    id: 'hist-2',
    orderNumber: 'CRG-8755',
    title: 'Commercial Server Racks (Dry Cargo)',
    date: 'Mar 07, 2:30 PM',
    cargoType: 'standard' as const,
    pickup: 'Westside Logistics Park',
    dropoff: 'DataCore Tier 4 Facility',
    distance: '24.1 km',
    duration: '41 min',
    baseFare: 840.0,
    surchargeTotal: 0,
    surcharges: [],
    totalPayout: 840.0,
    status: 'Completed',
  },
  {
    id: 'hist-3',
    orderNumber: 'CRG-8710',
    title: 'Temperature-Sensitive Insulin Batches',
    date: 'Mar 06, 11:15 AM',
    cargoType: 'cold_chain' as const,
    pickup: 'State Health Depot',
    dropoff: 'Metro Community Clinic',
    distance: '12.0 km',
    duration: '22 min',
    baseFare: 900.0,
    surchargeTotal: 150.0,
    surcharges: [
      {
        id: 'sur-hist-2',
        reason: 'Heavy Manual Carry (3 Flights)',
        amount: 150.0,
        status: 'approved' as const,
        requestedAt: 'Mar 06 10:45 AM',
        approvedAt: 'Mar 06 10:50 AM',
      },
    ],
    totalPayout: 1050.0,
    status: 'Completed',
    verifiedTemp: '3.6°C (Optimal)',
  },
];
